[package]
name = "seamless_gif_looping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1", features = ["derive"] }
console = "0.15.5"
gifski = "1.10.3"
indicatif = "0.17.3"
num_cpus = "1.15.0"
png = "0.17.7"
rayon = "1.7.0"
